title: Joonkee's Blog
description: Joonkee's Blog

url: https://joonkeekim.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
gems:
 - jekyll-paginate
 - jekyll-archives
 - jekyll-time-to-read
paginate: 5
# paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Archives
    url: /contact

social:
  github: joonkeekim
  email: joonkee0701@naver.com

google_analytics: "UA-58263416-1"